# Generated by Django 2.2 on 2019-11-14 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0004_auto_20191029_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmoment',
            name='medewerker',
            field=models.URLField(blank=True, help_text='URL-referentie naar een medewerker', max_length=1000),
        ),
        migrations.CreateModel(
            name='Medewerker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificatie', models.CharField(blank=True, db_index=True, help_text='Een korte unieke aanduiding van de MEDEWERKER.', max_length=24)),
                ('achternaam', models.CharField(blank=True, help_text='De achternaam zoals de MEDEWERKER die in het dagelijkse verkeer gebruikt.', max_length=200)),
                ('voorletters', models.CharField(blank=True, help_text='De verzameling letters die gevormd wordt door de eerste letter van alle in volgorde voorkomende voornamen.', max_length=20)),
                ('voorvoegsel_achternaam', models.CharField(blank=True, help_text='Dat deel van de geslachtsnaam dat voorkomt in Tabel 36 (GBA), voorvoegseltabel, en door een spatie van de geslachtsnaam is', max_length=10)),
                ('contactmoment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medewerker_identificatie', to='datamodel.ContactMoment')),
            ],
            options={
                'verbose_name': 'medewerker',
            },
        ),
    ]
