# Generated by Django 2.2.6 on 2019-11-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0006_auto_20191114_1141"),
    ]

    operations = [
        migrations.RenameField(
            model_name="klant", old_name="betrokkene", new_name="subject",
        ),
        migrations.RenameField(
            model_name="klant", old_name="betrokkene_type", new_name="subject_type",
        ),
    ]
