# Generated by Django 2.2.6 on 2019-11-21 14:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0008_objectverzoek_verzoek"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerzoekInformatieObject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "informatieobject",
                    models.URLField(
                        help_text="URL-referentie naar het INFORMATIEOBJECT (in de Documenten API) waarin (een deel van) het verzoek beschreven is of aanvullende informatie biedt bij het VERZOEK.",
                        max_length=1000,
                        verbose_name="informatieobject",
                    ),
                ),
                (
                    "verzoek",
                    models.ForeignKey(
                        help_text="URL-referentie naar het VERZOEK.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datamodel.Verzoek",
                    ),
                ),
            ],
            options={
                "verbose_name": "verzoekinformatieobject",
                "verbose_name_plural": "verzoekinformatieobjecten",
                "unique_together": {("verzoek", "informatieobject")},
            },
        ),
    ]
