# Generated by Django 2.2 on 2019-10-24 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("datamodel", "0002_auto_20191022_1012")]

    operations = [
        migrations.RenameField(
            model_name="klant", old_name="telefonnummer", new_name="telefoonnummer"
        )
    ]
