# Generated by Django 2.2 on 2019-10-29 12:58

from django.db import migrations, models
import django.db.models.deletion
import uuid
import vng_api_common.models


class Migration(migrations.Migration):

    dependencies = [("datamodel", "0003_auto_20191024_1008")]

    operations = [
        migrations.AlterModelOptions(
            name="contactmoment",
            options={
                "verbose_name": "contactmoment",
                "verbose_name_plural": "contactmomenten",
            },
        ),
        migrations.AlterModelOptions(
            name="klant",
            options={"verbose_name": "klant", "verbose_name_plural": "klanten"},
        ),
        migrations.RemoveField(model_name="contactmoment", name="zaak"),
        migrations.CreateModel(
            name="ObjectContactMoment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "object",
                    models.URLField(
                        help_text="URL-referentie naar het gerelateerde OBJECT (in een andere API)."
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[("zaak", "Zaak")],
                        help_text="Het type van het gerelateerde OBJECT.",
                        max_length=100,
                        verbose_name="objecttype",
                    ),
                ),
                (
                    "contactmoment",
                    models.ForeignKey(
                        help_text="URL-referentie naar het CONTACTMOMENT.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datamodel.ContactMoment",
                    ),
                ),
            ],
            options={
                "verbose_name": "object-contactmoment",
                "verbose_name_plural": "object-contactmomenten",
                "unique_together": {("contactmoment", "object")},
            },
            bases=(vng_api_common.models.APIMixin, models.Model),
        ),
    ]
