# Generated by Django 2.2.6 on 2019-12-06 15:07

from django.db import migrations, models
import django.db.models.deletion
import uuid
import vng_api_common.models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0010_contactmoment_onderwerp_links"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerzoekProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "product",
                    models.URLField(
                        blank=True,
                        help_text="URL-referentie naar het PRODUCT (in de Producten en Diensten API).",
                        null=True,
                    ),
                ),
                (
                    "product_code",
                    models.CharField(
                        help_text="De unieke code van het PRODUCT.", max_length=20
                    ),
                ),
                (
                    "verzoek",
                    models.ForeignKey(
                        help_text="URL-referentie naar het VERZOEK.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datamodel.Verzoek",
                    ),
                ),
            ],
            bases=(vng_api_common.models.APIMixin, models.Model),
        ),
    ]
