# Generated by Django 2.2.6 on 2019-12-18 11:31

from django.db import migrations, models
import vng_api_common.fields
import vng_api_common.validators


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0011_verzoekproduct"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactmoment",
            old_name="datumtijd",
            new_name="interactiedatum",
        ),
        migrations.RenameField(
            model_name="verzoek", old_name="datumtijd", new_name="interactiedatum",
        ),
        migrations.AddField(
            model_name="contactmoment",
            name="bronorganisatie",
            field=vng_api_common.fields.RSINField(
                default="000000000",
                help_text="Het RSIN van de Niet-natuurlijk persoon zijnde de organisatie die de klantinteractie heeft gecreeerd. Dit moet een geldig RSIN zijn van 9 nummers en voldoen aan https://nl.wikipedia.org/wiki/Burgerservicenummer#11-proef",
                max_length=9,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="klant",
            name="functie",
            field=models.CharField(
                blank=True, help_text="De functie van de klant.", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="verzoek",
            name="bronorganisatie",
            field=vng_api_common.fields.RSINField(
                default="000000000",
                help_text="Het RSIN van de Niet-natuurlijk persoon zijnde de organisatie die de klantinteractie heeft gecreeerd. Dit moet een geldig RSIN zijn van 9 nummers en voldoen aan https://nl.wikipedia.org/wiki/Burgerservicenummer#11-proef",
                max_length=9,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="verzoek",
            name="externe_identificatie",
            field=models.CharField(
                blank=True,
                help_text="De identificatie van het VERZOEK buiten de eigen organisatie.",
                max_length=40,
                validators=[vng_api_common.validators.AlphanumericExcludingDiacritic()],
            ),
        ),
        migrations.AddField(
            model_name="verzoek",
            name="identificatie",
            field=models.CharField(
                blank=True,
                help_text="De unieke identificatie van het VERZOEK binnen de organisatie die verantwoordelijk is voor de behandeling van het VERZOEK.",
                max_length=40,
                validators=[vng_api_common.validators.AlphanumericExcludingDiacritic()],
            ),
        ),
        migrations.AddField(
            model_name="verzoek",
            name="status",
            field=models.CharField(
                choices=[
                    ("ontvangen", "Ontvangen"),
                    ("in_behandeling", "In behandeling"),
                    ("afgehandeld", "Afgehandeld"),
                    ("afgewezen", "Afgewezen"),
                    ("ingetrokken", "Ingetrokken"),
                ],
                default="ontvangen",
                help_text="De waarden van de typering van de voortgang van afhandeling van een VERZOEK.",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="verzoekproduct",
            name="product",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL-referentie naar het PRODUCT (in de Producten en Diensten API).",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="verzoekproduct",
            name="product_code",
            field=models.CharField(
                blank=True, help_text="De unieke code van het PRODUCT.", max_length=20
            ),
        ),
        migrations.AlterUniqueTogether(
            name="verzoek", unique_together={("bronorganisatie", "identificatie")},
        ),
    ]
