# Generated by Django 2.2.11 on 2020-03-20 13:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0013_auto_20200318_1420"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmoment",
            name="interactiedatum",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="De datum en het tijdstip waarop de klantinteractie heeft plaatsgevonden.",
            ),
        ),
        migrations.AlterField(
            model_name="contactmoment",
            name="klant",
            field=models.ForeignKey(
                blank=True,
                help_text="URL-referentie naar een KLANT indien de klantinteractie niet anoniem is.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="datamodel.Klant",
            ),
        ),
        migrations.AlterField(
            model_name="contactmoment",
            name="tekst",
            field=models.TextField(
                blank=True,
                help_text="Een toelichting die inhoudelijk de klantinteractie van de klant beschrijft.",
            ),
        ),
        migrations.AlterField(
            model_name="contactmoment",
            name="voorkeurskanaal",
            field=models.CharField(
                blank=True,
                help_text="Het communicatiekanaal dat voor opvolging van de klantinteractie de voorkeur heeft van de KLANT.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="verzoek",
            name="interactiedatum",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="De datum en het tijdstip waarop de klantinteractie heeft plaatsgevonden.",
            ),
        ),
        migrations.AlterField(
            model_name="verzoek",
            name="klant",
            field=models.ForeignKey(
                blank=True,
                help_text="URL-referentie naar een KLANT indien de klantinteractie niet anoniem is.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="datamodel.Klant",
            ),
        ),
        migrations.AlterField(
            model_name="verzoek",
            name="tekst",
            field=models.TextField(
                blank=True,
                help_text="Een toelichting die inhoudelijk de klantinteractie van de klant beschrijft.",
            ),
        ),
        migrations.AlterField(
            model_name="verzoek",
            name="voorkeurskanaal",
            field=models.CharField(
                blank=True,
                help_text="Het communicatiekanaal dat voor opvolging van de klantinteractie de voorkeur heeft van de KLANT.",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="VerzoekContactMoment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "contactmoment",
                    models.ForeignKey(
                        help_text="URL-referentie naar het CONTACTMOMENT.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datamodel.ContactMoment",
                    ),
                ),
                (
                    "verzoek",
                    models.ForeignKey(
                        help_text="URL-referentie naar het VERZOEK.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datamodel.Verzoek",
                    ),
                ),
            ],
            options={
                "verbose_name": "verzoekcontactmoment",
                "verbose_name_plural": "verzoekcontactmomenten",
                "unique_together": {("verzoek", "contactmoment")},
            },
        ),
    ]
