# Generated by Django 2.2.11 on 2020-03-20 16:26

from django.db import migrations, models
import django.db.models.deletion
import vng_api_common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0014_auto_20200320_1323"),
    ]

    operations = [
        migrations.AlterField(
            model_name="klant",
            name="subject_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("natuurlijk_persoon", "Natuurlijk persoon"),
                    ("niet_natuurlijk_persoon", "Niet-natuurlijk persoon"),
                    ("vestiging", "Vestiging"),
                ],
                help_text="Type van de `subject`.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="NietNatuurlijkPersoon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inn_nnp_id",
                    vng_api_common.fields.RSINField(
                        blank=True,
                        help_text="Het door een kamer toegekend uniek nummer voor de INGESCHREVEN NIET-NATUURLIJK PERSOON",
                        max_length=9,
                    ),
                ),
                (
                    "ann_identificatie",
                    models.CharField(
                        blank=True,
                        help_text="Het door de gemeente uitgegeven unieke nummer voor een ANDER NIET-NATUURLIJK PERSOON",
                        max_length=17,
                    ),
                ),
                (
                    "statutaire_naam",
                    models.TextField(
                        blank=True,
                        help_text="Naam van de niet-natuurlijke persoon zoals deze is vastgelegd in de statuten (rechtspersoon) of in de vennootschapsovereenkomst is overeengekomen (Vennootschap onder firma of Commanditaire vennootschap).",
                        max_length=500,
                    ),
                ),
                (
                    "inn_rechtsvorm",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("besloten_vennootschap", "Besloten Vennootschap"),
                            (
                                "cooperatie_europees_economische_samenwerking",
                                "Cooperatie, Europees Economische Samenwerking",
                            ),
                            (
                                "europese_cooperatieve_venootschap",
                                "Europese Cooperatieve Venootschap",
                            ),
                            (
                                "europese_naamloze_vennootschap",
                                "Europese Naamloze Vennootschap",
                            ),
                            ("kerkelijke_organisatie", "Kerkelijke Organisatie"),
                            ("naamloze_vennootschap", "Naamloze Vennootschap"),
                            (
                                "onderlinge_waarborg_maatschappij",
                                "Onderlinge Waarborg Maatschappij",
                            ),
                            (
                                "overig_privaatrechtelijke_rechtspersoon",
                                "Overig privaatrechtelijke rechtspersoon",
                            ),
                            ("stichting", "Stichting"),
                            ("vereniging", "Vereniging"),
                            ("vereniging_van_eigenaars", "Vereniging van Eigenaars"),
                            (
                                "publiekrechtelijke_rechtspersoon",
                                "Publiekrechtelijke Rechtspersoon",
                            ),
                            ("vennootschap_onder_firma", "Vennootschap onder Firma"),
                            ("maatschap", "Maatschap"),
                            ("rederij", "Rederij"),
                            (
                                "commanditaire_vennootschap",
                                "Commanditaire vennootschap",
                            ),
                            (
                                "kapitaalvennootschap_binnen_eer",
                                "Kapitaalvennootschap binnen EER",
                            ),
                            (
                                "overige_buitenlandse_rechtspersoon_vennootschap",
                                "Overige buitenlandse rechtspersoon vennootschap",
                            ),
                            (
                                "kapitaalvennootschap_buiten_eer",
                                "Kapitaalvennootschap buiten EER",
                            ),
                        ],
                        help_text="De juridische vorm van de NIET-NATUURLIJK PERSOON.",
                        max_length=50,
                    ),
                ),
                (
                    "bezoekadres",
                    models.CharField(
                        blank=True,
                        help_text="De gegevens over het adres van de NIET-NATUURLIJK PERSOON",
                        max_length=1000,
                    ),
                ),
                (
                    "klant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="niet_natuurlijk_persoon",
                        to="datamodel.Klant",
                    ),
                ),
            ],
            options={"verbose_name": "niet-natuurlijk persoon",},
        ),
        migrations.AddField(
            model_name="subverblijfbuitenland",
            name="nietnatuurlijkpersoon",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_verblijf_buitenland",
                to="datamodel.NietNatuurlijkPersoon",
            ),
        ),
    ]
