# Generated by Django 2.2.11 on 2020-06-08 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0015_auto_20200320_1626"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmoment",
            name="vorig_contactmoment",
            field=models.OneToOneField(
                blank=True,
                help_text="URL-referentie naar het vorige CONTACTMOMENT.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="volgend_contactmoment",
                to="datamodel.ContactMoment",
            ),
        ),
    ]
