# Generated by Django 2.2.11 on 2020-06-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0015_auto_20200320_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectcontactmoment',
            name='object',
            field=models.URLField(help_text='URL-referentie naar het gerelateerde OBJECT (in een andere API).', max_length=1000),
        ),
        migrations.AlterField(
            model_name='objectverzoek',
            name='object',
            field=models.URLField(help_text='URL-referentie naar het gerelateerde OBJECT (in een andere API).', max_length=1000),
        ),
    ]
