# Generated by Django 2.2.11 on 2020-06-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0016_klantcontactmoment"),
    ]

    operations = [
        migrations.RemoveField(model_name="contactmoment", name="klant",),
    ]
